name: ci
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup FluentCI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: postgres
          args: start
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POSTGRES_USER: postgres
          POSTGRES_DB: demo_rails_test
      - name: check style + security
        run: |
          fluentci run --wasm ruby bundle_exec rubocop
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBY_VERSION: 3.1.4
      - name: Run tests
        run: |
          fluentci run --wasm ruby bundle_exec rails db:migrate
          fluentci run --wasm ruby bundle_exec rails db:seed
          fluentci run --wasm ruby bundle_exec rails test
          fluentci run --wasm ruby bundle_exec rspec spec
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RAILS_ENV: test
